FROM python:3.12-slim

RUN useradd -r -u 10001 -m appuser

WORKDIR /app

COPY non-vulnerable-app/python/app.py /app/app.py

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

CMD ["python", "app.py"]